### ISSUE TITLE
ApromoreDocker can't login with provided user and pw

### ISSUE THREAD

**Issue by ngs90** [apromore/ApromoreDocker#11]
Hi, 

I folllowed the instruction and the run "start.bat" seemed to succeed and Apromore prints "<DE0005I> Started plan 'org.apromore.root' version '1.1.0'". However, when I access the service via "http://localhost:9000" I can't login with the username and password provided (testuser:testuser).

Anyone else having problems with this?

In the logs I can see various issues like:

```
apromore_1            | [2019-06-14 08:07:25.774] region-dm-11                 <AG0000E> Application context creation failure for bundle 'org.apromore.apm-verification-osgi' version '1.1.0'. org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'apmVerificationConfig' defined in URL [bundleentry://263.fwk237351678/META-INF/spring/context.xml]: Could not resolve placeholder 'nusmv.path'
apromore_1            |         at org.springframework.beans.factory.config.PlaceholderConfigurerSupport.doProcessProperties(PlaceholderConfigurerSupport.java:209)
apromore_1            |         at org.springframework.context.support.PropertySourcesPlaceholderConfigurer.processProperties(PropertySourcesPlaceholderConfigurer.java:174)
apromore_1            |         at org.springframework.context.support.PropertySourcesPlaceholderConfigurer.postProcessBeanFactory(PropertySourcesPlaceholderConfigurer.java:151)
apromore_1            |         at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.invokeBeanFactoryPostProcessors(AbstractDelegatedExecutionApplicationContext.java:444)
apromore_1            |         at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.invokeBeanFactoryPostProcessors(AbstractDelegatedExecutionApplicationContext.java:414)
apromore_1            |         at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.invokeBeanFactoryPostProcessors(AbstractDelegatedExecutionApplicationContext.java:362)
apromore_1            |         at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext$3.run(AbstractDelegatedExecutionApplicationContext.java:254)
apromore_1            |         at org.eclipse.gemini.blueprint.util.internal.PrivilegedUtils.executeWithCustomTCCL(PrivilegedUtils.java:85)
apromore_1            |         at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.startRefresh(AbstractDelegatedExecutionApplicationContext.java:220)
apromore_1            |         at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor.stageOne(DependencyWaiterApplicationContextExecutor.java:224)
apromore_1            |         at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor.refresh(DependencyWaiterApplicationContextExecutor.java:177)
apromore_1            |         at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.refresh(AbstractDelegatedExecutionApplicationContext.java:157)
apromore_1            |         at org.eclipse.gemini.blueprint.extender.internal.activator.LifecycleManager$1.run(LifecycleManager.java:211)
apromore_1            |         at org.eclipse.virgo.kernel.agent.dm.ContextPropagatingTaskExecutor$2.run(ContextPropagatingTaskExecutor.java:95)
apromore_1            |         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
apromore_1            |         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
apromore_1            |         at java.lang.Thread.run(Thread.java:748)
```

```
apromore_1            |         at org.eclipse.virgo.web.core.internal.WebBundleLifecycleListener.onStarted(WebBundleLifecycleListener.java:132)
apromore_1            |         at org.eclipse.virgo.kernel.install.artifact.internal.StandardArtifactStateMonitor.onStarted(StandardArtifactStateMonitor.java:271)
apromore_1            |         at org.eclipse.virgo.kernel.install.artifact.internal.AbstractInstallArtifact.asyncStartSucceeded(AbstractInstallArtifact.java:319)
apromore_1            |         at org.eclipse.virgo.kernel.install.artifact.internal.AbstractInstallArtifact.access$0(AbstractInstallArtifact.java:316)
apromore_1            |         at org.eclipse.virgo.kernel.install.artifact.internal.AbstractInstallArtifact$StateMonitorSignal.signalSuccessfulCompletion(AbstractInstallArtifact.java:252)
apromore_1            |         at org.eclipse.virgo.nano.core.internal.BundleStartTracker$1.run(BundleStartTracker.java:140)
apromore_1            |         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
apromore_1            |         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
apromore_1            |         at java.lang.Thread.run(Thread.java:748)
apromore_1            | Caused by: org.eclipse.gemini.web.core.WebApplicationStartFailedException: org.eclipse.gemini.web.core.spi.ServletContainerException: Web application at '/editor' failed to start. Check the logs for more details.
apromore_1            |         at org.eclipse.gemini.web.internal.StandardWebApplication.start(StandardWebApplication.java:137)
apromore_1            |         at org.eclipse.virgo.web.core.internal.WebBundleLifecycleListener.onStarted(WebBundleLifecycleListener.java:122)
apromore_1            |         ... 8 common frames omitted
apromore_1            | Caused by: org.eclipse.gemini.web.core.spi.ServletContainerException: Web application at '/editor' failed to start. Check the logs for more details.
apromore_1            |         at org.eclipse.gemini.web.tomcat.internal.TomcatServletContainer.startWebApplication(TomcatServletContainer.java:133)
apromore_1            |         at org.eclipse.gemini.web.internal.StandardWebApplication.start(StandardWebApplication.java:109)
apromore_1            |         ... 9 common frames omitted
apromore_1            |
apromore_1            | [2019-06-14 08:08:27.505] start-signalling-3           <DE0006E> Start failed for plan 'org.apromore.editor' version '1.2.0'. org.eclipse.virgo.nano.deployer.api.core.DeploymentException: Web application failed to start
```

and when trying to create a new user in the system there seems to be issues with various sql tables missing: 

```
apromore_1            | [2019-06-14 08:08:50.462] start-signalling-1           <DE0005I> Started bundle 'org.apromore.merge-logic' version '1.1.0'.
apromore_1            | [2019-06-14 08:08:50.487] start-signalling-1           <DE0005I> Started bundle 'org.apromore.similaritysearch-logic' version '1.1.0'.
apromore_1            | [2019-06-14 08:08:50.500] start-signalling-1           <DE0005I> Started bundle 'org.apromore.similaritysearch-portal' version '1.1.0'.
apromore_1            | [2019-06-14 08:08:50.501] start-signalling-1           <DE0005I> Started plan 'org.apromore.plugin.similaritysearch' version '1.1.0'.
apromore_1            | [2019-06-14 08:08:50.507] start-signalling-1           <DE0005I> Started bundle 'org.apromore.plugin.merge-portal' version '1.1.0'.
apromore_1            | [2019-06-14 08:08:50.509] start-signalling-1           <DE0005I> Started plan 'org.apromore.plugin.merge' version '1.1.0'.
apromore_1            | [2019-06-14 08:08:50.530] start-signalling-1           <DE0005I> Started bundle 'org.apromore.manager' version '1.1.0'.
apromore_1            | [2019-06-14 08:08:50.531] start-signalling-1           <DE0005I> Started plan 'org.apromore.manager' version '1.1.0'.
apromore_1            | [2019-06-14 08:08:50.532] start-signalling-1           <DE0005I> Started plan 'org.apromore.root' version '1.1.0'.
apromore_1            | [2019-06-14 08:12:52,564] ERROR NewUserRegistrationHttpServletRequestHandler - Error with registering a new user!
apromore_1            | java.lang.Exception: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.4.1.v20121003-ad44345): org.eclipse.persistence.exceptions.DatabaseException
apromore_1            | Internal Exception: java.sql.BatchUpdateException: Table 'apromore.group' doesn't exist
apromore_1            | Error Code: 1146
apromore_1            | Query: ValueReadQuery(name="SEQ_GEN_IDENTITY" sql="SELECT LAST_INSERT_ID()"); nested exception is javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.4.1.v20121003-ad44345): org.eclipse.persistence.exceptions.DatabaseException
apromore_1            | Internal Exception: java.sql.BatchUpdateException: Table 'apromore.group' doesn't exist
apromore_1            | Error Code: 1146
apromore_1            | Query: ValueReadQuery(name="SEQ_GEN_IDENTITY" sql="SELECT LAST_INSERT_ID()")
apromore_1            |         at org.apromore.manager.client.ManagerServiceClient.writeUser(ManagerServiceClient.java:958) ~[manager-client-1.1.jar/:na]
apromore_1            |         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
apromore_1            |         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
apromore_1            |         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
apromore_1            |         at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
apromore_1            |         at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:318) ~[org.springframework.aop_3.1.0.RELEASE.jar:3.1.0.RELEASE]
apromore_1            |         at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.doInvoke(ServiceInvoker.java:56) ~[na:na]
apromore_1            |         at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.invoke(ServiceInvoker.java:60) ~[na:na]
apromore_1            |         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[org.springframework.aop_3.1.0.RELEASE.jar:3.1.0.RELEASE]
apromore_1            |         at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:131) ~[org.springframework.aop_3.1.0.RELEASE.jar:3.1.0.RELEASE]
apromore_1            |         at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:119) ~[org.springframework.aop_3.1.0.RELEASE.jar:3.1.0.RELEASE]
apromore_1            |         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[org.springframework.aop_3.1.0.RELEASE.jar:3.1.0.RELEASE]
apromore_1            |         at org.eclipse.gemini.blueprint.service.importer.support.LocalBundleContextAdvice.invoke(LocalBundleContextAdvice.java:57) ~[org.eclipse.gemini.blueprint.core_1.0.2.RELEASE.jar/:1.0.2.RELEASE]
apromore_1            |         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[org.springframework.aop_3.1.0.RELEASE.jar:3.1.0.RELEASE]
apromore_1            |         at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:131) ~[org.springframework.aop_3.1.0.RELEASE.jar:3.1.0.RELEASE]
apromore_1            |         at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:119) ~[org.springframework.aop_3.1.0.RELEASE.jar:3.1.0.RELEASE]
apromore_1            |         at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172) ~[org.springframework.aop_3.1.0.RELEASE.jar:3.1.0.RELEASE]
apromore_1            |         at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202) ~[org.springframework.aop_3.1.0.RELEASE.jar:3.1.0.RELEASE]
apromore_1            |         at com.sun.proxy.$Proxy228.writeUser(Unknown Source) ~[na:na]
apromore_1            |         at org.apromore.portal.servlet.NewUserRegistrationHttpServletRequestHandler.handleRequest(NewUserRegistrationHttpServletRequestHandler.java:73) ~[apromore-portal-1.1.war/:na]
apromore_1            |         at org.springframework.web.context.support.HttpRequestHandlerServlet.service(HttpRequestHandlerServlet.java:67) [org.springframework.web_3.1.0.RELEASE.jar:3.1.0.RELEASE]
apromore_1            |         at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [javax.servlet_3.0.0.v201112011016.jar:na]
apromore_1            |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [org.apache.catalina_7.0.61.jar:7.0.61]
apromore_1            |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [org.apache.catalina_7.0.61.jar:7.0.61]
apromore_1            |         at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [org.apache.tomcat.websocket_7.0.61.jar:7.0.61]
apromore_1            |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [org.apache.catalina_7.0.61.jar:7.0.61]
apromore_1            |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [org.apache.catalina_7.0.61.jar:7.0.61]
apromore_1            |         at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:186) [org.springframework.security.web-3.1.4.RELEASE.jar:3.1.4.RELEASE]
apromore_1            |         at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160) [org.springframework.security.web-3.1.4.RELEASE.jar:3.1.4.RELEASE]
apromore_1            |         at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346) [org.springframework.web_3.1.0.RELEASE.jar:3.1.0.RELEASE]
apromore_1            |         at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259) [org.springframework.web_3.1.0.RELEASE.jar:3.1.0.RELEASE]
apromore_1            |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [org.apache.catalina_7.0.61.jar:7.0.61]
apromore_1            |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [org.apache.catalina_7.0.61.jar:7.0.61]
apromore_1            |         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) [org.apache.catalina_7.0.61.jar:7.0.61]
apromore_1            |         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) [org.apache.catalina_7.0.61.jar:7.0.61]
apromore_1            |         at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505) [org.apache.catalina_7.0.61.jar:7.0.61]
apromore_1            |         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170) [org.apache.catalina_7.0.61.jar:7.0.61]
apromore_1            |         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) [org.apache.catalina_7.0.61.jar:7.0.61]
apromore_1            |         at org.eclipse.virgo.web.tomcat.support.ApplicationNameTrackingValve.invoke(ApplicationNameTrackingValve.java:33) [org.eclipse.virgo.web.tomcat.support_3.6.4.RELEASE.jar/:3.6.4.RELEASE]
apromore_1            |         at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950) [org.apache.catalina_7.0.61.jar:7.0.61]
apromore_1            |         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [org.apache.catalina_7.0.61.jar:7.0.61]
apromore_1            |         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423) [org.apache.catalina_7.0.61.jar:7.0.61]
apromore_1            |         at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079) [org.apache.coyote_7.0.61.jar:7.0.61]
apromore_1            |         at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620) [org.apache.coyote_7.0.61.jar:7.0.61]
apromore_1            |         at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318) [org.apache.coyote_7.0.61.jar:7.0.61]
apromore_1            |         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_212]
apromore_1            |         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_212]
apromore_1            |         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [org.apache.coyote_7.0.61.jar:7.0.61]
apromore_1            |         at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
apromore_1            | [2019-06-14 08:12:52,569] DEBUG BaseServletRequestHandler - Redirecting to '/login.zul?error=4'
```

**Comment by fgregg** [comment]
I'm having the same problem. Did you ever resolve @ngs90 ?

**Comment by verenich** [comment]
Hi @fgregg what version of Docker have you downloaded? I've tried the [latest (7.6) release](https://github.com/apromore/ApromoreDocker/releases/tag/v7.6) and I could not reproduce the issue
