### ISSUE TITLE
ApromoreDocker web apps fail to start

### ISSUE THREAD

**Issue by n2taylor** [apromore/ApromoreDocker#16]
**OS**: Mac OS X 10.15
**ApromoreDocker version**: v7.6
**Docker version**: 19.03.2
**docker-compose version**: 1.24.1

After running `./start`:

```
apromore_1   | [2019-10-28 18:04:20.410] region-dm-8                  <AG0000E> Application context creation failure for bundle 'org.apromore.manager' version '1.1.0'. org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Configuration problem: BundleContext is no longer valid
apromore_1   | Offending resource: URL [bundleentry://174.fwk1860944798/META-INF/spring/managerContext-jpa.xml]; nested exception is java.lang.IllegalStateException: BundleContext is no longer valid
apromore_1   | Offending resource: URL [bundleentry://174.fwk1860944798/META-INF/spring/managerContext-jpa.xml]; nested exception is org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: BundleContext is no longer valid
apromore_1   | Offending resource: URL [bundleentry://174.fwk1860944798/META-INF/spring/managerContext-jpa.xml]; nested exception is java.lang.IllegalStateException: BundleContext is no longer valid
apromore_1   | 	at org.springframework.beans.factory.parsing.FailFastProblemReporter.error(FailFastProblemReporter.java:68)
apromore_1   | 	at org.springframework.beans.factory.parsing.ReaderContext.error(ReaderContext.java:85)
apromore_1   | 	at org.springframework.beans.factory.parsing.ReaderContext.error(ReaderContext.java:76)
apromore_1   | 	at org.springframework.data.repository.config.RepositoryBeanDefinitionParser.handleError(RepositoryBeanDefinitionParser.java:84)
apromore_1   | 	at org.springframework.data.repository.config.RepositoryBeanDefinitionParser.parse(RepositoryBeanDefinitionParser.java:77)
apromore_1   | 	at org.springframework.beans.factory.xml.NamespaceHandlerSupport.parse(NamespaceHandlerSupport.java:73)
apromore_1   | 	at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1419)
apromore_1   | 	at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1409)
apromore_1   | 	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:184)
apromore_1   | 	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.doRegisterBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:140)
apromore_1   | 	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.registerBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:111)
apromore_1   | 	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefinitions(XmlBeanDefinitionReader.java:493)
apromore_1   | 	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:390)
apromore_1   | 	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:334)
apromore_1   | 	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:302)
apromore_1   | 	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:174)
apromore_1   | 	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:209)
apromore_1   | 	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:180)
apromore_1   | 	at org.eclipse.gemini.blueprint.context.support.OsgiBundleXmlApplicationContext.loadBeanDefinitions(OsgiBundleXmlApplicationContext.java:170)
apromore_1   | 	at org.eclipse.gemini.blueprint.context.support.OsgiBundleXmlApplicationContext.loadBeanDefinitions(OsgiBundleXmlApplicationContext.java:140)
apromore_1   | 	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:131)
apromore_1   | 	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:522)
apromore_1   | 	at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.access$800(AbstractDelegatedExecutionApplicationContext.java:60)
apromore_1   | 	at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext$3.run(AbstractDelegatedExecutionApplicationContext.java:242)
apromore_1   | 	at org.eclipse.gemini.blueprint.util.internal.PrivilegedUtils.executeWithCustomTCCL(PrivilegedUtils.java:85)
apromore_1   | 	at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.startRefresh(AbstractDelegatedExecutionApplicationContext.java:220)
apromore_1   | 	at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor.stageOne(DependencyWaiterApplicationContextExecutor.java:224)
apromore_1   | 	at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor.refresh(DependencyWaiterApplicationContextExecutor.java:177)
apromore_1   | 	at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.refresh(AbstractDelegatedExecutionApplicationContext.java:157)
apromore_1   | 	at org.eclipse.gemini.blueprint.extender.internal.activator.LifecycleManager$1.run(LifecycleManager.java:211)
apromore_1   | 	at org.eclipse.virgo.kernel.agent.dm.ContextPropagatingTaskExecutor$2.run(ContextPropagatingTaskExecutor.java:95)
apromore_1   | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
apromore_1   | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
apromore_1   | 	at java.lang.Thread.run(Thread.java:748)
apromore_1   | Caused by: org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: BundleContext is no longer valid
apromore_1   | Offending resource: URL [bundleentry://174.fwk1860944798/META-INF/spring/managerContext-jpa.xml]; nested exception is java.lang.IllegalStateException: BundleContext is no longer valid
apromore_1   | 	at org.springframework.beans.factory.parsing.FailFastProblemReporter.error(FailFastProblemReporter.java:68)
apromore_1   | 	at org.springframework.beans.factory.parsing.ReaderContext.error(ReaderContext.java:85)
apromore_1   | 	at org.springframework.beans.factory.parsing.ReaderContext.error(ReaderContext.java:76)
apromore_1   | 	at org.springframework.data.repository.config.RepositoryBeanDefinitionParser.handleError(RepositoryBeanDefinitionParser.java:84)
apromore_1   | 	at org.springframework.data.repository.config.RepositoryBeanDefinitionParser.registerGenericRepositoryFactoryBean(RepositoryBeanDefinitionParser.java:122)
apromore_1   | 	at org.springframework.data.repository.config.RepositoryBeanDefinitionParser.parse(RepositoryBeanDefinitionParser.java:71)
apromore_1   | 	... 29 common frames omitted
apromore_1   | Caused by: java.lang.IllegalStateException: BundleContext is no longer valid
apromore_1   | 	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.checkValid(BundleContextImpl.java:931)
apromore_1   | 	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.getServiceReference(BundleContextImpl.java:528)
apromore_1   | 	at org.eclipse.gemini.blueprint.io.internal.resolver.PackageAdminResolver$1.run(PackageAdminResolver.java:176)
apromore_1   | 	at org.eclipse.gemini.blueprint.io.internal.resolver.PackageAdminResolver$1.run(PackageAdminResolver.java:175)
apromore_1   | 	at java.security.AccessController.doPrivileged(Native Method)
apromore_1   | 	at org.eclipse.gemini.blueprint.io.internal.resolver.PackageAdminResolver.getPackageAdmin(PackageAdminResolver.java:173)
apromore_1   | 	at org.eclipse.gemini.blueprint.io.internal.resolver.PackageAdminResolver.getImportedBundles(PackageAdminResolver.java:66)
apromore_1   | 	at org.eclipse.gemini.blueprint.io.OsgiBundleResourcePatternResolver.findClassPathMatchingResources(OsgiBundleResourcePatternResolver.java:216)
apromore_1   | 	at org.eclipse.gemini.blueprint.io.OsgiBundleResourcePatternResolver.findResources(OsgiBundleResourcePatternResolver.java:153)
apromore_1   | 	at org.eclipse.gemini.blueprint.io.OsgiBundleResourcePatternResolver.getResources(OsgiBundleResourcePatternResolver.java:185)
apromore_1   | 	at org.eclipse.gemini.blueprint.context.support.AbstractOsgiBundleApplicationContext.getResources(AbstractOsgiBundleApplicationContext.java:439)
apromore_1   | 	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:227)
apromore_1   | 	at org.springframework.data.repository.config.RepositoryBeanDefinitionBuilder.detectCustomImplementation(RepositoryBeanDefinitionBuilder.java:154)
apromore_1   | 	at org.springframework.data.repository.config.RepositoryBeanDefinitionBuilder.registerCustomImplementation(RepositoryBeanDefinitionBuilder.java:116)
apromore_1   | 	at org.springframework.data.repository.config.RepositoryBeanDefinitionBuilder.build(RepositoryBeanDefinitionBuilder.java:97)
apromore_1   | 	at org.springframework.data.repository.config.RepositoryBeanDefinitionParser.registerGenericRepositoryFactoryBean(RepositoryBeanDefinitionParser.java:101)
apromore_1   | 	... 30 common frames omitted
```

Leading to a subsequent error message:

```
apromore_1   | [2019-10-28 18:07:33.402] start-signalling-3           <WE0005E> Failed to start web bundle 'org.apromore.filestore' version '1.1.0': consult serviceability/logs/log.log for further details.
apromore_1   | [2019-10-28 18:07:34.136] start-signalling-3           <DE0006E> Start failed for bundle 'org.apromore.filestore' version '1.1.0'. org.eclipse.virgo.nano.deployer.api.core.DeploymentException: Web application failed to start
apromore_1   | 	at org.eclipse.virgo.web.core.internal.WebBundleLifecycleListener.onStarted(WebBundleLifecycleListener.java:132)
apromore_1   | 	at org.eclipse.virgo.kernel.install.artifact.internal.StandardArtifactStateMonitor.onStarted(StandardArtifactStateMonitor.java:271)
apromore_1   | 	at org.eclipse.virgo.kernel.install.artifact.internal.AbstractInstallArtifact.asyncStartSucceeded(AbstractInstallArtifact.java:319)
apromore_1   | 	at org.eclipse.virgo.kernel.install.artifact.internal.AbstractInstallArtifact.access$0(AbstractInstallArtifact.java:316)
apromore_1   | 	at org.eclipse.virgo.kernel.install.artifact.internal.AbstractInstallArtifact$StateMonitorSignal.signalSuccessfulCompletion(AbstractInstallArtifact.java:252)
apromore_1   | 	at org.eclipse.virgo.nano.core.internal.BundleStartTracker$1.run(BundleStartTracker.java:140)
apromore_1   | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
apromore_1   | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
apromore_1   | 	at java.lang.Thread.run(Thread.java:748)
apromore_1   | Caused by: org.eclipse.gemini.web.core.WebApplicationStartFailedException: org.eclipse.gemini.web.core.spi.ServletContainerException: Web application at '/filestore' failed to start. Check the logs for more details.
apromore_1   | 	at org.eclipse.gemini.web.internal.StandardWebApplication.start(StandardWebApplication.java:137)
apromore_1   | 	at org.eclipse.virgo.web.core.internal.WebBundleLifecycleListener.onStarted(WebBundleLifecycleListener.java:122)
apromore_1   | 	... 8 common frames omitted
apromore_1   | Caused by: org.eclipse.gemini.web.core.spi.ServletContainerException: Web application at '/filestore' failed to start. Check the logs for more details.
apromore_1   | 	at org.eclipse.gemini.web.tomcat.internal.TomcatServletContainer.startWebApplication(TomcatServletContainer.java:133)
apromore_1   | 	at org.eclipse.gemini.web.internal.StandardWebApplication.start(StandardWebApplication.java:109)
apromore_1   | 	... 9 common frames omitted
apromore_1   |
apromore_1   | [2019-10-28 18:07:37.448] start-signalling-3           <DE0006E> Start failed for plan 'org.apromore.filestore' version '1.1.0'. org.eclipse.virgo.nano.deployer.api.core.DeploymentException: Web application failed to start
apromore_1   | 	at org.eclipse.virgo.web.core.internal.WebBundleLifecycleListener.onStarted(WebBundleLifecycleListener.java:132)
apromore_1   | 	at org.eclipse.virgo.kernel.install.artifact.internal.StandardArtifactStateMonitor.onStarted(StandardArtifactStateMonitor.java:271)
apromore_1   | 	at org.eclipse.virgo.kernel.install.artifact.internal.AbstractInstallArtifact.asyncStartSucceeded(AbstractInstallArtifact.java:319)
apromore_1   | 	at org.eclipse.virgo.kernel.install.artifact.internal.AbstractInstallArtifact.access$0(AbstractInstallArtifact.java:316)
apromore_1   | 	at org.eclipse.virgo.kernel.install.artifact.internal.AbstractInstallArtifact$StateMonitorSignal.signalSuccessfulCompletion(AbstractInstallArtifact.java:252)
apromore_1   | 	at org.eclipse.virgo.nano.core.internal.BundleStartTracker$1.run(BundleStartTracker.java:140)
apromore_1   | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
apromore_1   | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
apromore_1   | 	at java.lang.Thread.run(Thread.java:748)
apromore_1   | Caused by: org.eclipse.gemini.web.core.WebApplicationStartFailedException: org.eclipse.gemini.web.core.spi.ServletContainerException: Web application at '/filestore' failed to start. Check the logs for more details.
apromore_1   | 	at org.eclipse.gemini.web.internal.StandardWebApplication.start(StandardWebApplication.java:137)
apromore_1   | 	at org.eclipse.virgo.web.core.internal.WebBundleLifecycleListener.onStarted(WebBundleLifecycleListener.java:122)
apromore_1   | 	... 8 common frames omitted
apromore_1   | Caused by: org.eclipse.gemini.web.core.spi.ServletContainerException: Web application at '/filestore' failed to start. Check the logs for more details.
apromore_1   | 	at org.eclipse.gemini.web.tomcat.internal.TomcatServletContainer.startWebApplication(TomcatServletContainer.java:133)
apromore_1   | 	at org.eclipse.gemini.web.internal.StandardWebApplication.start(StandardWebApplication.java:109)
apromore_1   | 	... 9 common frames omitted
```

**Comment by ibrahimahdy** [comment]
Hi @n2taylor 

We need to have a look at the full log so we figure out the error cause, to do so please do the following:

1. PULL latest changes from https://github.com/apromore/ApromoreDocker
2. Run `./start` if it still fails, then
3. Open a new terminal window in the same working directory `ApromoreDocker` (Don't close the previous one) and run `./copyLog` which will add a new file to the ApromoreDocker working directory called: `log.log`, please upload this file here, it has the complete output log, so we can have a look.

Kind regards,
