### ISSUE TITLE
ApromoreDocker on Ubuntu, failed to deploy apromore editor and BPMN 2.0 editor not loading

### ISSUE THREAD

**Issue by denoide1** [apromore/ApromoreDocker#6]
i can access with admin/password but when i try to visualize a BPMN 2.0 file, the page doesn't load and the console logs 

```
zk.wpd:8732 Failed to load resource: the server responded with a status of 404 (Not Found)
send @ zk.wpd:8732
zk.wpd:8179 Uncaught SyntaxError: Unexpected token <
    at eval (<anonymous>)
    at zk.wpd:666
    at Function.globalEval (zk.wpd:667)
    at text script (zk.wpd:8482)
    at ajaxConvert (zk.wpd:8457)
    at done (zk.wpd:8221)
    at callback (zk.wpd:8804)
    at Object.send (zk.wpd:8810)
    at Function.ajax (zk.wpd:8172)
    at Function._evalUrl (zk.wpd:6779)
ext-all.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
file-upload.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
xtheme-gray.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
theme_norm.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
theme_norm_signavio.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
xtheme-smoky.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
custom-style.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
ext-all.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
file-upload.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
xtheme-gray.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
theme_norm.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
theme_norm_signavio.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
xtheme-smoky.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
custom-style.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```

when i check the server log there is only this error

```
apromore_1            |         at org.eclipse.gemini.web.internal.StandardWebApplication.start(StandardWebApplication.java:109)
apromore_1            |         ... 9 common frames omitted
apromore_1            | 
apromore_1            | [2019-01-20 01:40:35.044] start-signalling-2           <DE0006E> Start failed for plan 'org.apromore.editor' version '1.1.0'. org.eclipse.virgo.nano.deployer.api.core.DeploymentException: Web application failed to start
apromore_1            |         at org.eclipse.virgo.web.core.internal.WebBundleLifecycleListener.onStarted(WebBundleLifecycleListener.java:132)
apromore_1            |         at org.eclipse.virgo.kernel.install.artifact.internal.StandardArtifactStateMonitor.onStarted(StandardArtifactStateMonitor.java:271)
apromore_1            |         at org.eclipse.virgo.kernel.install.artifact.internal.AbstractInstallArtifact.asyncStartSucceeded(AbstractInstallArtifact.java:319)
apromore_1            |         at org.eclipse.virgo.kernel.install.artifact.internal.AbstractInstallArtifact.access$0(AbstractInstallArtifact.java:316)
apromore_1            |         at org.eclipse.virgo.kernel.install.artifact.internal.AbstractInstallArtifact$StateMonitorSignal.signalSuccessfulCompletion(AbstractInstallArtifact.java:252)
apromore_1            |         at org.eclipse.virgo.nano.core.internal.BundleStartTracker$1.run(BundleStartTracker.java:140)
apromore_1            |         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
apromore_1            |         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
apromore_1            |         at java.lang.Thread.run(Thread.java:748)
apromore_1            | Caused by: org.eclipse.gemini.web.core.WebApplicationStartFailedException: org.eclipse.gemini.web.core.spi.ServletContainerException: Web application at '/editor' failed to start. Check the logs for more details.
apromore_1            |         at org.eclipse.gemini.web.internal.StandardWebApplication.start(StandardWebApplication.java:137)
apromore_1            |         at org.eclipse.virgo.web.core.internal.WebBundleLifecycleListener.onStarted(WebBundleLifecycleListener.java:122)
apromore_1            |         ... 8 common frames omitted
apromore_1            | Caused by: org.eclipse.gemini.web.core.spi.ServletContainerException: Web application at '/editor' failed to start. Check the logs for more details.
apromore_1            |         at org.eclipse.gemini.web.tomcat.internal.TomcatServletContainer.startWebApplication(TomcatServletContainer.java:133)
apromore_1            |         at org.eclipse.gemini.web.internal.StandardWebApplication.start(StandardWebApplication.java:109)
apromore_1            |         ... 9 common frames omitted
```

what can i do to solve ?

**Comment by verenich** [comment]
what is your system config? OS, java version? Do you have problems with other plugins as well?

**Comment by denoide1** [comment]
> what is your system config? java version? Do you have problems with other plugins as well?

i have java 8 v201, ubuntu 18.04, Docker CE for Ubuntu.
I have only problems with this plugin and the BPMN 2.0 Editor
